name: E2E Tests

on:
  push:
    branches:
      - master
      - main
      - dev
      - production
      - staging
      - demo

  pull_request:
    branches: [ '*' ]


jobs:
  merge-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Fetch target branch
        run: git fetch origin main:main

      - name: Merge target branch into PR
        run: git merge origin/main

      - name: Run tests
        run: |
          if ! grep -q '"test:e2e"' package.json; then
            echo "E2E tests script not found. Skip this step" 
            exit 0
          else
            npm run test:e2e
          fi
